repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data. It is run with --no-update to get around some strange permission issues with trufflehog.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --fail --no-update'
        language: system
        stages: ["pre-commit", "pre-push"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.6
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]

  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.0.1
    hooks:
      - id: pyrefly-typecheck-system
        name: Pyrefly (type checking)
        pass_filenames: false # Recommended to do full repo checks. However, you can change this to `true` to only check changed files

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.12
    hooks:
      - id: uv-lock